// gen-sde extracts killmail-relevant type data from the EVE SDE SQLite
// database and writes a static Go map to internal/enrichment/sde_gen.go.
//
// Usage: go run ./cmd/gen-sde              (uses ./eve.db by default)
//        go run ./cmd/gen-sde -db /path/to/eve.db
package main

import (
	"database/sql"
	"flag"
	"fmt"
	"log"
	"os"
	"sort"
	"text/template"
	"time"

	_ "modernc.org/sqlite"
)

const outPath = "internal/enrichment/sde_gen.go"

// Killmail-relevant EVE category IDs.
// These are the only categories that appear in killmail fittings/ships.
var relevantCategories = []int{6, 7, 8, 18, 20, 32, 65, 66, 87}

// sdeRow holds the data extracted for one type.
type sdeRow struct {
	TypeID      int64
	TypeName    string
	GroupID     int64
	GroupName   string
	CategoryID  int64
	CatName     string
	MetaLevel   int
	MetaGroupID int64
	MetaGroup   string
}

func main() {
	dbPath := flag.String("db", "./eve.db", "path to EVE SDE sqlite database")
	flag.Parse()

	db, err := sql.Open("sqlite", fmt.Sprintf("file:%s?mode=ro&_foreign_keys=off", *dbPath))
	if err != nil {
		log.Fatalf("open db: %v", err)
	}
	defer db.Close()

	if err := db.Ping(); err != nil {
		log.Fatalf("ping db: %v", err)
	}

	rows, err := queryTypes(db)
	if err != nil {
		log.Fatalf("query: %v", err)
	}
	log.Printf("extracted %d types", len(rows))

	if err := writeGoFile(rows); err != nil {
		log.Fatalf("write output: %v", err)
	}
	log.Printf("wrote %s", outPath)
}

func queryTypes(db *sql.DB) ([]sdeRow, error) {
	// Build the IN clause for category IDs.
	catClause := ""
	for i, id := range relevantCategories {
		if i > 0 {
			catClause += ","
		}
		catClause += fmt.Sprintf("%d", id)
	}

	query := fmt.Sprintf(`
SELECT
    t.typeID,
    COALESCE(t.typeName, ''),
    COALESCE(t.groupID, 0),
    COALESCE(g.name, ''),
    COALESCE(g.categoryID, 0),
    COALESCE(c.name, ''),
    COALESCE(t.metaLevel, 0),
    COALESCE(t.metaGroupID, 0),
    COALESCE(mg.metaGroupName, '')
FROM invtypes t
LEFT JOIN invgroups g ON g.groupID = t.groupID
LEFT JOIN invcategories c ON c.categoryID = g.categoryID
LEFT JOIN invmetagroups mg ON mg.metaGroupID = t.metaGroupID
WHERE t.published = 1
  AND g.categoryID IN (%s)
ORDER BY t.typeID
`, catClause)

	res, err := db.Query(query)
	if err != nil {
		return nil, err
	}
	defer res.Close()

	var rows []sdeRow
	for res.Next() {
		var r sdeRow
		if err := res.Scan(
			&r.TypeID, &r.TypeName,
			&r.GroupID, &r.GroupName,
			&r.CategoryID, &r.CatName,
			&r.MetaLevel, &r.MetaGroupID, &r.MetaGroup,
		); err != nil {
			return nil, err
		}
		rows = append(rows, r)
	}
	return rows, res.Err()
}

var goTmpl = template.Must(template.New("").Funcs(template.FuncMap{
	"fmtRow": func(r sdeRow) string {
		return fmt.Sprintf("\t%d: {%q, %d, %q, %d, %q, %d, %d, %q},",
			r.TypeID, r.TypeName, r.GroupID, r.GroupName,
			r.CategoryID, r.CatName, r.MetaLevel, r.MetaGroupID, r.MetaGroup)
	},
}).Parse(`// Code generated by cmd/gen-sde. DO NOT EDIT.
// Source: EVE SDE (categories: ship, module, charge, drone, implant, subsystem, structure, fighter)
// Generated: {{ .Date }}

package enrichment

// sdeType holds enrichment data for a single EVE type ID.
type sdeType struct {
	TypeName    string
	GroupID     int64
	GroupName   string
	CategoryID  int64
	CatName     string
	MetaLevel   int
	MetaGroupID int64
	MetaGroup   string
}

// sdeTypes maps EVE type IDs to their enrichment data.
var sdeTypes = map[int64]sdeType{
{{- range .Rows}}
{{ fmtRow . }}
{{- end}}
}
`))

func writeGoFile(rows []sdeRow) error {
	sort.Slice(rows, func(i, j int) bool { return rows[i].TypeID < rows[j].TypeID })

	f, err := os.Create(outPath)
	if err != nil {
		return err
	}
	defer f.Close()

	return goTmpl.Execute(f, map[string]interface{}{
		"Date": time.Now().UTC().Format("2006-01-02"),
		"Rows": rows,
	})
}
