// gen-systems fetches all solar system names from ESI and writes a static Go
// map to internal/enrichment/systems_gen.go.
//
// Usage: go run ./cmd/gen-systems
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"
	"sort"
	"sync"
	"text/template"
	"time"
)

const (
	esiBase   = "https://esi.evetech.net"
	userAgent = "zkill-bot/1.0 (gen-systems)"
	workers   = 20
	outPath   = "internal/enrichment/systems_gen.go"
)

var client = &http.Client{Timeout: 10 * time.Second}

func main() {
	log.Println("fetching system ID list...")
	ids, err := fetchSystemIDs()
	if err != nil {
		log.Fatalf("fetch system IDs: %v", err)
	}
	log.Printf("got %d system IDs, fetching names...", len(ids))

	names := fetchSystemNames(ids)
	log.Printf("resolved %d system names", len(names))

	if err := writeGoFile(names); err != nil {
		log.Fatalf("write output: %v", err)
	}
	log.Printf("wrote %s", outPath)
}

func fetchSystemIDs() ([]int64, error) {
	req, _ := http.NewRequest(http.MethodGet, esiBase+"/v1/universe/systems/?datasource=tranquility", nil)
	req.Header.Set("User-Agent", userAgent)
	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	var ids []int64
	if err := json.NewDecoder(resp.Body).Decode(&ids); err != nil {
		return nil, err
	}
	return ids, nil
}

type systemInfo struct {
	Name string `json:"name"`
}

func fetchSystemNames(ids []int64) map[int64]string {
	type result struct {
		id   int64
		name string
	}

	jobs := make(chan int64, len(ids))
	results := make(chan result, len(ids))

	var wg sync.WaitGroup
	for range workers {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for id := range jobs {
				name, err := fetchSystemName(id)
				if err != nil {
					log.Printf("warn: system %d: %v", id, err)
					continue
				}
				results <- result{id, name}
			}
		}()
	}

	for _, id := range ids {
		jobs <- id
	}
	close(jobs)

	go func() {
		wg.Wait()
		close(results)
	}()

	out := make(map[int64]string, len(ids))
	done := 0
	for r := range results {
		out[r.id] = r.name
		done++
		if done%1000 == 0 {
			log.Printf("  %d / %d", done, len(ids))
		}
	}
	return out
}

func fetchSystemName(id int64) (string, error) {
	url := fmt.Sprintf("%s/v4/universe/systems/%d/?datasource=tranquility", esiBase, id)
	req, _ := http.NewRequest(http.MethodGet, url, nil)
	req.Header.Set("User-Agent", userAgent)

	for attempt := range 3 {
		resp, err := client.Do(req)
		if err != nil {
			if attempt < 2 {
				time.Sleep(time.Duration(attempt+1) * time.Second)
				continue
			}
			return "", err
		}
		defer resp.Body.Close()
		if resp.StatusCode == http.StatusTooManyRequests {
			time.Sleep(2 * time.Second)
			continue
		}
		var info systemInfo
		if err := json.NewDecoder(resp.Body).Decode(&info); err != nil {
			return "", err
		}
		return info.Name, nil
	}
	return "", fmt.Errorf("all attempts failed")
}

var goTemplate = template.Must(template.New("").Parse(`// Code generated by cmd/gen-systems. DO NOT EDIT.

package enrichment

// solarSystemNames maps solar system IDs to their in-game names.
// Generated from ESI /v1/universe/systems/ on {{ .Date }}.
var solarSystemNames = map[int64]string{
{{- range .Entries}}
	{{.ID}}: {{printf "%q" .Name}},
{{- end}}
}
`))

type entry struct {
	ID   int64
	Name string
}

func writeGoFile(names map[int64]string) error {
	// Sort by ID for deterministic output.
	entries := make([]entry, 0, len(names))
	for id, name := range names {
		entries = append(entries, entry{id, name})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].ID < entries[j].ID })

	f, err := os.Create(outPath)
	if err != nil {
		return err
	}
	defer f.Close()

	return goTemplate.Execute(f, map[string]interface{}{
		"Date":    time.Now().UTC().Format("2006-01-02"),
		"Entries": entries,
	})
}
